Profile: HCENPractitioner
Parent: UYPractitioner
Id: hcen-practitioner
Title: "Perfil Profesional de Salud para HCEN"
Description: "Una persona que está directa o indirectamente involucrada en la provisión de atención médica."

* photo 0..0
* identifier 1..*
* identifier[ci] 1..1
* name 1..*

// Descripciones del ODS, adaptadas a las rutas FHIR R4 y al contexto HCEN.
* id ^short = "ID lógico de este artefacto."
* id ^definition = "ID lógico de este artefacto."
* meta ^short = "Metadatos sobre el recurso."
* meta ^definition = "Metadatos sobre el recurso."
* implicitRules ^short = "Conjunto de reglas bajo las cuales se creó este contenido."
* implicitRules ^definition = "Conjunto de reglas bajo las cuales se creó este contenido."
* language ^short = "Idioma del contenido del recurso."
* language ^definition = "Idioma del contenido del recurso."
* text ^short = "Resumen del recurso en texto para interpretación humana."
* text ^definition = "Resumen del recurso en texto para interpretación humana."
* contained ^short = "Recursos inline."
* contained ^definition = "Recursos inline."
* extension ^short = "Contenido adicional definido por implementaciones."
* extension ^definition = "Contenido adicional definido por implementaciones."
* modifierExtension ^short = "Extensiones que no pueden ser ignoradas."
* modifierExtension ^definition = "Extensiones que no pueden ser ignoradas."
* identifier ^short = "Un identificador para esta persona en este rol."
* identifier ^definition = "Un identificador para esta persona en este rol."
* identifier[ci] ^short = "Cédula de identidad del profesional."
* identifier[ci] ^definition = "Cédula de identidad del profesional."
* active ^short = "Si el registro de este profesional está activo."
* active ^definition = "Si el registro de este profesional está activo."
* name ^short = "El nombre o nombres asociados con el profesional."
* name ^definition = "El nombre o nombres asociados con el profesional."
* telecom ^short = "Detalles de contacto de la persona."
* telecom ^definition = "Detalles de contacto de la persona."
* telecom[phone] ^short = "Detalles de teléfono de contacto."
* telecom[phone] ^definition = "Detalles de teléfono de contacto."
* telecom[email] ^short = "Detalles de correo electrónico de contacto."
* telecom[email] ^definition = "Detalles de correo electrónico de contacto."
* address ^short = "Una o más direcciones para el individuo."
* address ^definition = "Una o más direcciones para el individuo."
* address[uyAddress] ^short = "Dirección física en Uruguay."
* address[uyAddress] ^definition = "Dirección física en Uruguay."
* gender ^short = "Sexo administrativo."
* gender ^definition = "Sexo administrativo."
* birthDate ^short = "La fecha de nacimiento del profesional."
* birthDate ^definition = "La fecha de nacimiento del profesional."
* photo ^short = "Imagen del profesional."
* photo ^definition = "Imagen del profesional."
* qualification ^short = "Certificaciones oficiales, títulos, licencias o matrículas del profesional."
* qualification ^definition = "Certificaciones oficiales, títulos, licencias o matrículas del profesional."
* qualification.identifier ^short = "Identificador oficial de la cualificación o matrícula."
* qualification.identifier ^definition = "Identificador oficial de la cualificación o matrícula."
* qualification.code ^short = "Codificación de la cualificación."
* qualification.code ^definition = "Codificación de la cualificación."
* qualification.period ^short = "Periodo durante el cual la cualificación es válida."
* qualification.period ^definition = "Periodo durante el cual la cualificación es válida."
* qualification.issuer ^short = "Organización que otorgó o regula la cualificación."
* qualification.issuer ^definition = "Organización que otorgó o regula la cualificación."
* communication ^short = "Idiomas que el profesional puede usar para comunicarse con los pacientes."
* communication ^definition = "Idiomas que el profesional puede usar para comunicarse con los pacientes."
* . ^short = "Perfil Profesional de Salud para HCEN"
* . ^definition = "Una persona que está directa o indirectamente involucrada en la provisión de atención médica."
