Profile: HCENOrganization
Parent: UYOrganization
Id: hcen-organization
Title: "Perfil Organización para HCEN"
Description: "Una agrupación de personas u organizaciones con un propósito común."

* identifier 1..*
* identifier[organizationId] 1..1
* identifier[organizationId] only HCENAAIdentifier
* identifier[organizationId] ^short = "Identificador único de la organización en HCEN"
* name 1..1

// Descripciones del ODS, adaptadas a las rutas FHIR R4 y al contexto HCEN.
* id ^short = "ID lógico de este artefacto."
* id ^definition = "ID lógico de este artefacto."
* meta ^short = "Metadatos sobre el recurso."
* meta ^definition = "Metadatos sobre el recurso."
* implicitRules ^short = "Conjunto de reglas bajo las cuales se creó este contenido."
* implicitRules ^definition = "Conjunto de reglas bajo las cuales se creó este contenido."
* language ^short = "Idioma del contenido del recurso."
* language ^definition = "Idioma del contenido del recurso."
* text ^short = "Resumen del recurso en texto para interpretación humana."
* text ^definition = "Resumen del recurso en texto para interpretación humana."
* contained ^short = "Recursos inline."
* contained ^definition = "Recursos inline."
* extension ^short = "Extensiones."
* extension ^definition = "Extensiones."
* modifierExtension ^short = "Extensiones que no pueden ser ignoradas."
* modifierExtension ^definition = "Extensiones que no pueden ser ignoradas."
* identifier ^short = "Identificadores de la organización."
* identifier ^definition = "Identificadores de la organización."
* active ^short = "Si el registro de la organización sigue activo."
* active ^definition = "Si el registro de la organización sigue activo."
* type ^short = "Tipo de organización."
* type ^definition = "Tipo de organización."
* name ^short = "Nombre utilizado para la organización."
* name ^definition = "Nombre utilizado para la organización."
* alias ^short = "Lista de nombres alternativos de la organización."
* alias ^definition = "Lista de nombres alternativos de la organización."
* telecom ^short = "Detalles de contacto de la organización."
* telecom ^definition = "Detalles de contacto de la organización."
* telecom[phone] ^short = "Detalles de teléfono de contacto."
* telecom[phone] ^definition = "Detalles de teléfono de contacto."
* telecom[email] ^short = "Detalles de correo electrónico de contacto."
* telecom[email] ^definition = "Detalles de correo electrónico de contacto."
* address ^short = "Una o más direcciones de la organización."
* address ^definition = "Una o más direcciones de la organización."
* address[uyAddress] ^short = "Dirección física en Uruguay."
* address[uyAddress] ^definition = "Dirección física en Uruguay."
* partOf ^short = "Organización de la cual forma parte esta organización."
* partOf ^definition = "Organización de la cual forma parte esta organización."
* contact ^short = "Contacto de la organización para un propósito específico."
* contact ^definition = "Contacto de la organización para un propósito específico."
* contact.purpose ^short = "El tipo de propósito del contacto."
* contact.purpose ^definition = "El tipo de propósito del contacto."
* contact.name ^short = "Nombre asociado con el contacto."
* contact.name ^definition = "Nombre asociado con el contacto."
* contact.telecom ^short = "Detalles de contacto de la organización."
* contact.telecom ^definition = "Detalles de contacto de la organización."
* contact.telecom[phone] ^short = "Detalles de teléfono de contacto."
* contact.telecom[phone] ^definition = "Detalles de teléfono de contacto."
* contact.telecom[email] ^short = "Detalles de correo electrónico de contacto."
* contact.telecom[email] ^definition = "Detalles de correo electrónico de contacto."
* contact.address ^short = "Dirección del contacto de la organización."
* contact.address ^definition = "Dirección física o postal del contacto de la organización, representada mediante UYAddress."
* endpoint ^short = "Endpoints técnicos que proveen acceso a servicios operados por la organización."
* endpoint ^definition = "Endpoints técnicos que proveen acceso a servicios operados por la organización."
* . ^short = "Perfil Organización para HCEN"
* . ^definition = "Una agrupación de personas u organizaciones con un propósito común."

* identifier[organizationId] ^definition = "Identificador único de la organización en HCEN"
