Profile: HCENPractitionerRole
Parent: UYPractitionerRole
Id: hcen-practitioner-role
Title: "Perfil Rol del Profesional de Salud para HCEN"
Description: "Roles y organizaciones específicos para los cuales el profesional está autorizado a proveer servicios."

* practitioner 1..1
* practitioner only Reference(HCENPractitioner)
* organization 1..1
* organization only Reference(HCENOrganization)
* code MS
* specialty MS
* location MS
// healthcareService conserva la cardinalidad base: no modelar no implica prohibir.

// Descripciones del ODS, adaptadas a las rutas FHIR R4 y al contexto HCEN.
* id ^short = "ID lógico de este artefacto."
* id ^definition = "ID lógico de este artefacto."
* meta ^short = "Metadatos sobre el recurso."
* meta ^definition = "Metadatos sobre el recurso."
* implicitRules ^short = "Conjunto de reglas bajo las cuales se creó este contenido."
* implicitRules ^definition = "Conjunto de reglas bajo las cuales se creó este contenido."
* language ^short = "Idioma del contenido del recurso."
* language ^definition = "Idioma del contenido del recurso."
* text ^short = "Resumen del recurso en texto para interpretación humana."
* text ^definition = "Resumen del recurso en texto para interpretación humana."
* contained ^short = "Recursos inline."
* contained ^definition = "Recursos inline."
* extension ^short = "Extensiones."
* extension ^definition = "Extensiones."
* modifierExtension ^short = "Extensiones que no pueden ser ignoradas."
* modifierExtension ^definition = "Extensiones que no pueden ser ignoradas."
* identifier ^short = "Identificadores específicos para este rol/lugar."
* identifier ^definition = "Identificadores específicos para este rol/lugar."
* active ^short = "Si el registro de este rol está activo."
* active ^definition = "Si el registro de este rol está activo."
* period ^short = "El periodo de tiempo durante el cual el profesional está autorizado a actuar en este rol."
* period ^definition = "El periodo de tiempo durante el cual el profesional está autorizado a actuar en este rol."
* practitioner ^short = "Profesional que provee los servicios para la organización."
* practitioner ^definition = "Profesional que provee los servicios para la organización."
* organization ^short = "La organización donde se proveen los servicios."
* organization ^definition = "La organización donde se proveen los servicios."
* code ^short = "Roles que este profesional está autorizado a desempeñar."
* code ^definition = "Roles que este profesional está autorizado a desempeñar."
* specialty ^short = "Especialidades específicas que el profesional ejerce en este rol."
* specialty ^definition = "Especialidades específicas que el profesional ejerce en este rol."
* location ^short = "Lugares físicos donde este profesional provee servicios."
* location ^definition = "Lugares físicos donde este profesional provee servicios."
* healthcareService ^short = "Servicios de salud que este rol provee de forma específica."
* healthcareService ^definition = "Servicios de salud que este rol provee de forma específica."
* telecom ^short = "Detalles de contacto de la persona."
* telecom ^definition = "Detalles de contacto de la persona."
* telecom[phone] ^short = "Detalles de teléfono de contacto."
* telecom[phone] ^definition = "Detalles de teléfono de contacto."
* telecom[email] ^short = "Detalles de correo electrónico de contacto."
* telecom[email] ^definition = "Detalles de correo electrónico de contacto."
* availableTime ^short = "Tiempos en los que el lugar/servicio está disponible."
* availableTime ^definition = "Tiempos en los que el lugar/servicio está disponible."
* availableTime.daysOfWeek ^short = "Días de la semana que aplica."
* availableTime.daysOfWeek ^definition = "Días de la semana que aplica."
* availableTime.allDay ^short = "Si está disponible las 24 horas."
* availableTime.allDay ^definition = "Si está disponible las 24 horas."
* availableTime.availableStartTime ^short = "Hora de apertura."
* availableTime.availableStartTime ^definition = "Hora de apertura."
* availableTime.availableEndTime ^short = "Hora de cierre."
* availableTime.availableEndTime ^definition = "Hora de cierre."
* notAvailable ^short = "Periodos en los que no está disponible por razones específicas."
* notAvailable ^definition = "Periodos en los que no está disponible por razones específicas."
* notAvailable.description ^short = "Razón por la que no está disponible."
* notAvailable.description ^definition = "Razón por la que no está disponible."
* notAvailable.during ^short = "Periodo de tiempo de no disponibilidad."
* notAvailable.during ^definition = "Periodo de tiempo de no disponibilidad."
* availabilityExceptions ^short = "Descripción textual de anomalías en la disponibilidad."
* availabilityExceptions ^definition = "Descripción textual de anomalías en la disponibilidad."
* endpoint ^short = "Endpoints técnicos que proveen acceso a servicios para este rol."
* endpoint ^definition = "Endpoints técnicos que proveen acceso a servicios para este rol."
* . ^short = "Perfil Rol del Profesional de Salud para HCEN"
* . ^definition = "Roles y organizaciones específicos para los cuales el profesional está autorizado a proveer servicios."
